name: learn-github-actions
on: [push,pull_request]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    - name: Check for @nocommit
      uses: itsvs/no-merge-action@releases/v0.2
      with:
        keyword: "aaaa"