name: "Block @nocommit Merges"
on: [pull_request]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - name: Check for @nocommit
      uses: itsvs/no-merge-action@releases/v0.2
      with:
        github-token: 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
        keyword: "@nocommit"