name: "Check PR for word"
on: [pull_request]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - name: Check PR
      uses: JJ/github-pr-contains-action@releases/v0
      with:
        github-token: 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
        bodyDoesNotContain: "Delete this"
        bodyContains: 'Test'
        diffContains: 'Test'
        filesChanged: 1
        linesChanged: 1