name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    - name: action-git-diff-suggestions
      uses: getsentry/action-git-diff-suggestions@v1
      with:
        message: "レビューしました"