name: text_lint_test

on: push


jobs:
  text_lint_test:
    name: text_lint_test
    runs-on: ubuntu-latest

    steps:
        #reviewdogのアクション
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

        #textlintを動かすためのnodeアクション
      - uses: actions/setup-node@v2

      - uses: actions/checkout@v2

      - name: cache-node-modules
        #stepsが失敗(文章の乱れ)した場合でもcacheを取得するようにする
        uses: pat-s/always-upload-cache@v2.1.3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-

      # textlint textlint-rule-preset-smarthr textlint-rule-prh
      - name: Install textlint
        run:  'npm install --save-dev textlint textlint-rule-preset-smarthr textlint-rule-prh textlint-rule-ng-word textlint-plugin-html'

        # npm install -g textlint textlint-rule-ng-word
      - name: Install dependent module
        run: |
          npm install
          npm install textlint-plugin-html


        # textlint を走らせる
          # npx textlint -f checkstyle "docs/*.md" >> .textlint.log
      - name: キーワードチェック
        run: |
            npx textlint --rule textlint-rule-ng-word "docs/*"


      # textlintで文章上のミスがあった場合のみ、reviewdogを実行させるようにする
      - name: Run reviewdog
        if: failure()
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat .textlint.log | reviewdog -f=checkstyle -name="textlint" -reporter="github-pr-review"
